packages:
  - "."

minimumReleaseAgeExclude:
  - postcss@8.5.26
  - brace-expansion@5.0.9
  - nanoid@3.3.18

overrides:
  brace-expansion@>=4.0.0 <5.0.9: 5.0.12
  nanoid@<3.3.17: 3.3.19
  postcss@<=8.5.22: 8.5.28
  vite@*: "catalog:"
  vitest@*: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.0
  vitest: 5.0.1
  vite-plus: 1.0.0-rc.0
  "@vitest/coverage-v8": 5.0.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
