name: Scan

on:
  pull_request:
  workflow_call:
  schedule:
    - cron: "17 6 * * 1"
  workflow_dispatch:

permissions: {}

concurrency:
  group: scan-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  scan:
    permissions:
      contents: read
    uses: uinaf/.github/.github/workflows/scan.yml@5cb5234c5395e37a1c876619bbe5d7cb8938bda3 # v2.0.0
